[package]
name = "rdirstat-gui"
version = "0.1.0"
edition = "2021"
description = "A fast disk space analyzer (GUI)"
license = "MIT"
repository = "https://github.com/AndyGybels/rdirstat"

[dependencies]
rdirstat-core = { path = "../rdirstat-core" }
eframe = "0.31"
egui_extras = "0.31"

[package.metadata.deb]
section = "utils"
assets = [
    ["target/release/rdirstat-gui", "usr/bin/", "755"],
]
